# Generated by Django 2.0.5 on 2018-05-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authorid',
        ),
    ]
