# Generated by Django 2.0.5 on 2018-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
        ('articles', '0006_remove_article_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='members',
            field=models.ManyToManyField(related_name='habits', to='profiles.Profile'),
        ),
    ]
