# Generated by Django 2.0.5 on 2018-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-score',)},
        ),
        migrations.AddField(
            model_name='article',
            name='end_time',
            field=models.DateField(blank=True, default='2018-01-01'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_time',
            field=models.DateField(blank=True, default='2018-01-01'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(),
        ),
    ]
