# Generated by Django 2.0.5 on 2018-05-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180512_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateField(blank=True, default='2018-01-01'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, default='2018-01-01'),
        ),
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.TimeField(blank=True, default='24:00'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
