# Generated by Django 2.0.5 on 2018-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180512_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ispublic',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='article',
            name='sendnotification',
            field=models.IntegerField(default='0'),
        ),
    ]
