# Generated by Django 2.0.5 on 2018-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
