# Generated by Django 2.0.5 on 2018-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_blog_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ispublic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sendnotification',
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
    ]
