# Generated by Django 2.0.5 on 2018-05-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20180512_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='send_notification',
            field=models.IntegerField(default=1),
        ),
    ]
