# Generated by Django 2.0.5 on 2018-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20180512_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
